# Generated by Django 4.2 on 2023-06-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_user_name_blog_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_post',
            new_name='BlogPost',
        ),
    ]
