# Generated by Django 4.2 on 2023-06-20 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_blog_post_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 20, 8, 35, 12, 464549, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
