# Generated by Django 4.2 on 2023-06-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_blogpost_created_date_blogpost_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_draft',
            field=models.CharField(choices=[('is_draft', 'is_draft'), ('not_draft', 'not_draft')], max_length=20),
        ),
    ]
